### ISSUE TITLE
[TypeError]  Cannot call a class as a function

### ISSUE THREAD

**Issue by terry47** [chankamlam/chinese-search#1]
Hi there, 

I'm the new guys in NodeJS. I installed chinese-search and run the example which provided, I've got the error "TypeError: Cannot call a class as a function". What should i do  ? 

Thanks 

Terry

**Error**
/home/htdocs/XXXXXXXX/terry/node_modules/chinese-search/dist/index.js:34
function _classCallCheck(instance, Constructor) { if (!(instance instanceof Constructor)) { throw new TypeError("Cannot call a class as a function"); } }
                                                                                            ^

TypeError: Cannot call a class as a function
    at _classCallCheck (/home/htdocs/XXXXXXXX/terry/node_modules/chinese-search/dist/index.js:34:99)
    at Object.Engine (/home/htdocs/XXXXXXXX/terry/node_modules/chinese-search/dist/index.js:137:9)
    at Object.<anonymous> (/home/htdocs/XXXXXXXX/terry/terry.js:26:17)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Function.Module.runMain (module.js:676:10)
    at startup (bootstrap_node.js:187:16)

**Comment by chankamlam** [comment]
is that u import the module in ES6

**Comment by chankamlam** [comment]
sorry, some mistake in doc, it needs to be new a search engine like this:new search.Engine(opt)
